version: "3.3"

volumes:
  db_data_volume: { }

services:
  db:
    image: mariadb
    restart: always
    ports:
      - 3406:3306
    volumes:
      - type: volume
        source: db_data_volume
        target: /var/lib/mysql
      - type: bind
        source: ./sql_inits/
        target: /docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=abcd
      - MYSQL_DATABASE=hpm
